name: Docker Image CI

on:
  push:
    branches: [ main ]
  schedule:
  - cron:  '00 6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the image
      run: docker build . --file kubectl-1-21.Dockerfile --tag demtag/kubectl:1.21
    - name: Login to registry
      run: docker login --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push the image
      run: docker push demtag/kubectl:1.21
